### ISSUE TITLE
[Troubleshooting Help] Unable to get AnimationTree to work

### ISSUE THREAD

**Issue by Jonchun** [rayxuln/spine-runtime-for-godot#14]
[godot.zip](https://github.com/rayxuln/spine-runtime-for-godot/files/4907299/godot.zip)

Sorry that the code is a bit of a mess -- I was porting some old code I have from other projects and trying to integrate the Spine runtime.

Everything we care about happens in `Character/Player/Player.tscn`

I've created a "wrapper" called `CharacterSkin` which is going to be my own Skinning for my characters separate from Spine.

With that stated, on to my problem:
I've created an `AnimationTree` and an `AnimationPlayer` similarly to the examples. I currently have 2 animation states, `idle` and `walk`.

In `_physics_process`, I try doing:
```
	if true:
		anim_playback.travel("walk")
	else:
		anim_playback.travel("idle")
```
which is the same as what the example has (constantly travels to one of the animation nodes every frame)

However, my animation partially plays once and then stops/freezes. For some reason, if I go into the Remote tab in my scene and uncheck `active` on the `AnimationTree` node, it starts animating fine. I have no idea why it works in the example but not in mine.

I have no idea if this is a bug with this spine-runtime port or if I'm doing something silly which is why I'm posting here for help.

**Comment by rayxuln** [comment]
![image](https://user-images.githubusercontent.com/20488881/87235414-88af5680-c40e-11ea-8127-67637b5ace09.png)

You should set the track update mode in the animation player to discrete, otherwise it will set the current_animations all the time which will call set_animation function all the time and this function is supposed to be called once if you want to play a animation.

[godot.zip](https://github.com/rayxuln/spine-runtime-for-godot/files/4907745/godot.zip)

**Comment by Jonchun** [comment]
That was exactly it. Thank you.
